Feature/refactroring
diamandv/20methods pull request #3
Opened 2023-11-10 15:03 UTC by diamandv

if you see it - i did it!) Would be more!

2023-11-10 16:38 UTC, BogdanParashchak requested changes

2023-11-10 16:38 UTC, BogdanParashchak commented on src/main/java/Starter.java
to be deleted
we dont't need it any more bacause of JUnit tests

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        assertEquals(a,b,c);
formatting

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        assertEquals(a,b,c);
formatting

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        assertEquals(2,actualIndex);
formatting

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>          expectedArray.add(8);
List<Integer> expectedArray = List.of(......)

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>          ArrayList<Integer> actualArray = someTwentyMethods.findMultipleNumbersOfArray(integersArray, integer);
List Integer actualArray = someTwentyMethods.findMultipleNumbersOfArray(integersArray, integer);

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>      }
all the occurences of
ArrayList<Integer> expectedArray =
and
ArrayList<Integer> actualArray =
replace with
List<Integer> expectedArray = 
and
List<Integer> actualArray =

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        ArrayList<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
List actual......

2023-11-10 16:38 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        ArrayList<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
List = .....

2023-11-10 20:56 UTC, diamandv commented on src/main/java/Starter.java
done

2023-11-10 20:57 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        assertEquals(a,b,c);
done

2023-11-10 20:57 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        assertEquals(a,b,c);
done

2023-11-10 20:57 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        assertEquals(2,actualIndex);
done

2023-11-11 07:17 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>          expectedArray.add(8);
in futher commits

2023-11-11 07:17 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>          ArrayList<Integer> actualArray = someTwentyMethods.findMultipleNumbersOfArray(integersArray, integer);
in futher commits please

2023-11-11 07:17 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        ArrayList<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
in futher commits please

2023-11-11 07:17 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        ArrayList<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
in futher commits please

2023-11-11 07:18 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>      }
in futher commits please

2023-11-11 07:19 UTC, BogdanParashchak approved these changes

2023-11-11 16:10 UTC, merged