Refactoring
diamandv/20methods pull request #4
Opened 2023-11-11 19:23 UTC by diamandv

2023-11-11 19:29 UTC, diamandv commented
edit tasks and tests from 11 to 15 inclusive

2023-11-11 20:03 UTC, diamandv commented
found mistake in task 15 - rerair in next commit

2023-11-11 20:49 UTC, BogdanParashchak requested changes

2023-11-11 20:49 UTC, BogdanParashchak commented on src/main/java/SomeTwentyMethods.java
> +    public boolean checkIfYearIsLeap(int year) {
https://stackoverflow.com/questions/3874350/naming-conventions-for-java-methods-that-return-boolean
better way is to name it 'isLeap'

2023-11-11 20:49 UTC, BogdanParashchak commented on src/main/java/SomeTwentyMethods.java
> +            for (int j = i + 1; j < bytes.length; j++) {
TDD in action)))

2023-11-11 20:49 UTC, BogdanParashchak commented on src/main/java/SomeTwentyMethods.java
> +            } catch (ArithmeticException e) {
1. better approch is to inform user where problem occured, for example:
ArytmeticException("cannot multiply: " + intArray1[i] + " and " + intArray1[i] + " at index " + i );
2. separate test neded for the case of ArytmeticException: https://www.baeldung.com/junit-assert-exception

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        boolean actualLeap = someTwentyMethods.checkIfYearIsLeap(year);
isLeap

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        boolean actualLeap = someTwentyMethods.checkIfYearIsLeap(year);
isLeap

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        boolean actualLeap = someTwentyMethods.checkIfYearIsLeap(year);
isLeap

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        boolean actualLeap = someTwentyMethods.checkIfYearIsLeap(year);
isLeap

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        boolean actualLeap = someTwentyMethods.checkIfYearIsLeap(year);
isLeap

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> expectedArray = List.of(-2147483648, 4, 8);  //this part of code is not beautiful but work
expectedList

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualArray = someTwentyMethods.findTheArrayValuesWhichAreDivisibleByANumberWithoutARemainder(integersArray, integer);
1. actualList
2.  not 'findTheArrayValue.....' but 'findListOfValues' or much better not to mention collection you use, for example 'findValues'

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +    void givenIntAndIntArray_whenFindTheArrayValuesWhichAreDivisibleByAGivenIntWithoutARemainder_thenReturnListOfFoundValues() {
not 'findTheArrayValue.....' but 'findListOfValues' or much better not to mention collection you use, for example 'findValues.....'

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>      }
see previous comment regarding using of word 'array' where you actually return list

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
this is good example of naming of variables (expectedIntegers, actualIntegers)
but 'getArrayOf...' to be renamed to 'getNonMatchingIndexes'

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
>          expectedIntegers.add(2);
List.of

2023-11-11 20:49 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
rename method

2023-11-11 20:49 UTC, BogdanParashchak commented on src/main/java/SomeTwentyMethods.java
> +    public List<Integer> findTheArrayValuesWhichAreDivisibleByANumberWithoutARemainder(int[] integers, int number) {
findValuesWhich.......
bacause you return not array but list

2023-11-11 20:49 UTC, BogdanParashchak commented on src/main/java/SomeTwentyMethods.java
> +            } catch (ArithmeticException e) {
TDD in action))))

2023-11-11 20:54 UTC, BogdanParashchak requested changes

2023-11-11 20:54 UTC, BogdanParashchak commented on src/main/java/SomeTwentyMethods.java
> +        if ((checkIfTwoIntArraysAreNull(intArray1, intArray2))
https://stackoverflow.com/questions/12960554/java-boolean-getters-is-vs-are
isEachNull

2023-11-11 20:54 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +    }
check all places where you return list but your methods and test methods contain incorrect 'array'

2023-11-11 21:00 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +            for (int j = i + 1; j < bytes.length; j++) {
))) true

2023-11-11 21:37 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +    }
"intArray1" renamed to "integers"

2023-11-11 21:38 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +            } catch (ArithmeticException e) {
totally agree with you ))

2023-11-11 21:44 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +    public List<Integer> findTheArrayValuesWhichAreDivisibleByANumberWithoutARemainder(int[] integers, int number) {
I called it like this, because I have arrays in input, and looking for values in arrays
maybe then I'll call method " returnValuesWhich..."

2023-11-11 21:48 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +    public boolean checkIfYearIsLeap(int year) {
done

2023-11-11 21:50 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        boolean actualLeap = someTwentyMethods.checkIfYearIsLeap(year);
done

2023-11-11 21:57 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> expectedArray = List.of(-2147483648, 4, 8);  //this part of code is not beautiful but work
done

2023-11-11 21:59 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualArray = someTwentyMethods.findTheArrayValuesWhichAreDivisibleByANumberWithoutARemainder(integersArray, integer);
findValuesWhich....

2023-11-11 22:01 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +    void givenIntAndIntArray_whenFindTheArrayValuesWhichAreDivisibleByAGivenIntWithoutARemainder_thenReturnListOfFoundValues() {
done

2023-11-11 22:03 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +    public List<Integer> findTheArrayValuesWhichAreDivisibleByANumberWithoutARemainder(int[] integers, int number) {
called it - findValuesWhich...

2023-11-11 22:06 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
can be like this? - getNonMatchingIndexesFromTwoArrays

2023-11-11 22:08 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
done

2023-11-11 22:08 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
getNonMatchingIndexes - named it like this

2023-11-11 22:11 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +        if ((checkIfTwoIntArraysAreNull(intArray1, intArray2))
done

2023-11-11 22:12 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
>          expectedIntegers.add(2);
done

2023-11-12 21:04 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +            } catch (ArithmeticException e) {
done
deleted 2 previous tests with oveflow, because in this case cant return empty array

2023-11-13 07:40 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        List<Integer> actualIntegers = someTwentyMethods.getArrayOfNonMatchingIndexes(intArray1, intArray2);
getNonMatchingIndexes - looks good

2023-11-13 07:53 UTC, BogdanParashchak approved these changes

2023-11-13 08:02 UTC, merged