refactoring: edit tasks 15 and 18 with tests
diamandv/20methods pull request #5
Opened 2023-11-14 19:24 UTC by diamandv

2023-11-15 14:46 UTC, BogdanParashchak requested changes

2023-11-15 14:46 UTC, BogdanParashchak commented on src/main/java/SomeTwentyMethods.java
>          int[] result = new int[integers1.length];
can it be done on-fly
try not create new array but insert new values in existing array

2023-11-16 08:23 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
> +            if (longValue1 * longValue2 > Integer.MAX_VALUE || longValue1 * longValue2 < Integer.MIN_VALUE) {
done

2023-11-16 10:58 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
>          int[] result = new int[integers1.length];
done

2023-11-16 11:01 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
>          if (checkIfTwoCharArraysAreNull(charArray1, charArray2)) {
done

2023-11-16 11:02 UTC, diamandv commented on src/main/java/SomeTwentyMethods.java
>      public boolean compareTwoCharArrays(char[] charArray1, char[] charArray2) {
done

2023-11-16 11:27 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +    }
done

2023-11-16 13:44 UTC, BogdanParashchak requested changes

2023-11-16 13:44 UTC, BogdanParashchak commented on src/test/java/SomeTwentyMethodsTest.java
> +        }
formatting:
        for (int integer : actualIntegers) {
            assertTrue(integer >= lowerBorder);
            assertTrue(integer <= upperBorder);
        }

2023-11-16 21:13 UTC, diamandv commented on src/test/java/SomeTwentyMethodsTest.java
> +        }
formated

2023-11-17 09:31 UTC, BogdanParashchak approved these changes

2023-11-17 09:31 UTC, merged